# Generated by Django 3.1 on 2020-10-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetonp',
            name='answer',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10),
        ),
    ]
