# Generated by Django 3.1 on 2020-10-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0002_auto_20201010_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetonp',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
