# Generated by Django 3.1 on 2020-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0006_aetonp_idiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='aetonp',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
