# Generated by Django 3.1 on 2020-10-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0008_aetonp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetonp',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
