# Generated by Django 3.1 on 2020-10-16 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interest_app', '0018_aetoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aetoc',
            name='type',
            field=models.CharField(default='Annual Effective to Continuous Rate', max_length=50),
        ),
        migrations.AlterField(
            model_name='aetoep',
            name='type',
            field=models.CharField(default='Annual Effective to Effective Per Period Rate', max_length=50),
        ),
        migrations.AlterField(
            model_name='aetonp',
            name='type',
            field=models.CharField(default='Annual Effective to Nominal Per Period Rate', max_length=50),
        ),
        migrations.CreateModel(
            name='EPtoAE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.DecimalField(decimal_places=5, max_digits=10)),
                ('ip', models.DecimalField(decimal_places=5, max_digits=10)),
                ('idiv', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('answer', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('description', models.CharField(default='', max_length=50)),
                ('type', models.CharField(default='Effective Per Period to Annual Effective Rate', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
