# Generated by Django 3.1 on 2020-10-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0020_eptoep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eptoep',
            old_name='p1',
            new_name='pone',
        ),
        migrations.RenameField(
            model_name='eptoep',
            old_name='p2',
            new_name='ptwo',
        ),
    ]
