# Generated by Django 3.1 on 2020-10-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0026_nptoep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nptoep',
            name='type',
            field=models.CharField(default='Nominal Per Period to Effective Per Period Rate', max_length=50),
        ),
    ]
