# Generated by Django 3.1 on 2020-11-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvm_app', '0018_consannuadvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consannuadvav',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvav',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvav',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvav',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvav',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvav',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvc',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvc',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvc',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvc',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvc',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvc',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvn',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvn',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvn',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvn',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvn',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvn',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvx',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvx',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvx',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvx',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvx',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuadvx',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrav',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrav',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrav',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrav',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrav',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrav',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrc',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrc',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrc',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrc',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrc',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrc',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrn',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrn',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrn',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrn',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrn',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrn',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrx',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrx',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrx',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrx',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrx',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannuarrx',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannupv',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannupv',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannupv',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannupv',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='consannupv',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='j',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='jdiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuadvav',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='j',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='jdiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannuarrav',
            name='x',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannupv',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannupv',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannupv',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannupv',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='incannupv',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompav',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompav',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompav',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompav',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompav',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompi',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompi',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompi',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompi',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompi',
            name='pv',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompn',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompn',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompn',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompn',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcompn',
            name='pv',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcomppv',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcomppv',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcomppv',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcomppv',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvcomppv',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpav',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpav',
            name='c',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpav',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpav',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpav',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpi',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpi',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpi',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpi',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpi',
            name='pv',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpn',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpn',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpn',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpn',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimpn',
            name='pv',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimppv',
            name='answer',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimppv',
            name='av',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimppv',
            name='i',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimppv',
            name='idiv',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='singinvsimppv',
            name='n',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
